/* 
JTrayiconWrap.h
Copyright (C) 2004 Hendrik Muhs 
Java TrayIcon interface written by Hendrik Muhs   
 
 Permission is hereby granted, free of charge, to any person obtaining a copy of 
this software and associated documentation files (the "Software"), to deal in the Software without 
restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, 
sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is 
furnished to do so, subject to the following conditions:
 
The above copyright notice and this permission notice shall be included in all 
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, 
INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A 
PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR 
COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER 
IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION 
WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/


/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtrayicon */

#ifndef _Included_jtrayicon
#define _Included_jtrayicon
#ifdef __cplusplus
extern "C"
{
#endif
/*
 * Class:     jtrayicon
 * Method:    tray_icon_new
 * Signature: (Ljava/lang/String;)I
 */



	JNIEXPORT jlong JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1new (JNIEnv * jenv,
								jobject obj,
								jstring jarg1,
								jstring
								jarg2);
/*
 * Class:     jtrayicon
 * Method:    tray_icon_new_from_data
 * Signature: (Ljava/lang/String;)I
 */



	JNIEXPORT jlong JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1new_1from_1data (JNIEnv * jenv,
								jobject obj,
								jstring jarg1,
								jbyteArray
								jarg2);

	
/*
 * Class:     jtrayicon
 * Method:    tray_icon_remove
 * Signature: (Ljava/lang/String;)I
 */



	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1remove (JNIEnv * jenv,
								jobject obj,
								jlong jarg1);

	
/*
 * Class:     jtrayicon
 * Method:    tray_icon_send_message
 * Signature: (JLjava/lang/String;J)I
 */

	JNIEXPORT jint JNICALL
		Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1send_1message (JNIEnv * jenv,
							  jobject  obj,
							  jlong jarg1,
							  jlong jarg2,
							  jstring jarg3,
							  jlong jarg4);
/*
 * Class:     jtrayicon
 * Method:    tray_icon_cancel_message
 * Signature: (I)V
 */
	JNIEXPORT void JNICALL
		Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1cancel_1message (JNIEnv * jenv,
							    jobject  obj,
							    jlong jarg1,
							    jint jarg2);


/*
 * Class:     jtrayicon
 * Method:    tray_icon_set_image
 * Signature: (JLjava/lang/String;J)V
 */

	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1set_1image
		(JNIEnv * jenv, jobject  obj, jlong jarg1, jstring jarg2);


/*
 * Class:     jtrayicon
 * Method:    tray_icon_set_image
 * Signature: (JLjava/lang/String;J)V
 */

	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1set_1image_1from_1data
		(JNIEnv * jenv, jobject  obj, jlong jarg1, jbyteArray jarg2);

/*
 * Class:     jtrayicon
 * Method:    tray_icon_init
 * Signature: (JLjava/lang/String;J)V
 */
	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1init
		(JNIEnv * jenv, jobject  obj);

/*
 * Class:     jtrayicon
 * Method:    tray_icon_run
 * Signature: (JLjava/lang/String;J)V
 */
	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1run
		(JNIEnv * jenv, jobject  obj);
		
/*
 * Class:     jtrayicon
 * Method:    tray_icon_stop
 * Signature: (JLjava/lang/String;J)V
 */
	JNIEXPORT void JNICALL Java_de_asuhm_trayicon_JTrayiconWrap_tray_1icon_1stop
		(JNIEnv * jenv, jobject  obj);



#ifdef __cplusplus
}
#endif
#endif
